"""
Script to update the Word template to use [Hook] as standalone paragraphs
instead of embedded in a sentence structure.

The old format was:
    "[MemberName] is a [Age]-year-old [Gender] with past medical history of 
    [MedicalHistory], who presented to the [PlaceofService] on [DOS] for [Hook]."

The new format should be:
    "[Hook]"

Where [Hook] is now a complete 2-paragraph opening generated by the LLM.
"""

from docx import Document
import re
import shutil
from pathlib import Path

def fix_template(template_path: str, output_path: str = None):
    """Fix the template to use [Hook] as standalone paragraphs."""
    
    # Backup original
    if output_path is None:
        output_path = template_path
        backup_path = template_path.replace('.docx', '_backup.docx')
        shutil.copy(template_path, backup_path)
        print(f"Backed up to: {backup_path}")
    
    doc = Document(template_path)
    
    # Pattern to find the old sentence structure containing [Hook]
    # This looks for paragraph text that contains both demographic info AND [Hook]
    old_patterns = [
        # Pattern: "[MemberName] is a [Age]-year-old... for [Hook]"
        r'\[MemberName\].*who presented.*\[Hook\]',
        # Pattern: Any text before [Hook] that ends with "for" or "with complaints of"
        r'.*(?:for|with complaints of)\s*\[Hook\]',
    ]
    
    fixed_count = 0
    
    for para in doc.paragraphs:
        original_text = para.text
        
        # Check if this paragraph contains the old embedded [Hook] structure
        if '[Hook]' in original_text or '[Complaint]' in original_text:
            # If the paragraph has more than just [Hook], it's the old format
            hook_only = original_text.strip() in ['[Hook]', '[Complaint]', '[Hook].', '[Complaint].']
            
            if not hook_only and ('[Hook]' in original_text or '[Complaint]' in original_text):
                print(f"\nFound old format paragraph:")
                print(f"  Original: {original_text[:200]}...")
                
                # Replace the entire paragraph with just [Hook]
                para.clear()
                para.add_run('[Hook]')
                fixed_count += 1
                
                print(f"  Fixed to: [Hook]")
    
    doc.save(output_path)
    print(f"\nSaved to: {output_path}")
    print(f"Fixed {fixed_count} paragraph(s)")
    
    return fixed_count

def inspect_template(template_path: str):
    """Inspect the template to find where [Hook] is used."""
    doc = Document(template_path)
    
    print(f"\nInspecting: {template_path}\n")
    print("=" * 60)
    
    for i, para in enumerate(doc.paragraphs):
        text = para.text.strip()
        if text:
            # Highlight paragraphs with placeholders
            if '[' in text and ']' in text:
                print(f"\nParagraph {i} (has placeholders):")
                print(f"  {text[:300]}{'...' if len(text) > 300 else ''}")
            elif 'member' in text.lower() or 'midnight' in text.lower():
                print(f"\nParagraph {i} (appeal content):")
                print(f"  {text[:200]}{'...' if len(text) > 200 else ''}")

if __name__ == '__main__':
    import sys
    
    template_path = 'appeal_templates/Template.docx'
    
    if len(sys.argv) > 1 and sys.argv[1] == '--inspect':
        inspect_template(template_path)
    else:
        print("First, let's inspect the template:")
        inspect_template(template_path)
        
        print("\n" + "=" * 60)
        response = input("\nDo you want to fix the template? (y/n): ")
        if response.lower() == 'y':
            fix_template(template_path)
        else:
            print("No changes made.")
